<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup Condition=" '$(OS)' != 'Windows_NT' ">
		<TargetFrameworks>net10.0</TargetFrameworks>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(OS)' == 'Windows_NT' ">
		<TargetFrameworks>net10.0;net48</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\ServiceWire\ServiceWire.csproj" />
	</ItemGroup>

</Project>
